server:
  port: 8090

spring:
  application:
    name: lifetech-backend
  
  profiles:
    active: development
    
  main:
    allow-bean-definition-overriding: true
  
  datasource:
    url: jdbc:postgresql://localhost:5433/finance_admin
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
        
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
        
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
      
  redis:
    host: localhost
    port: 6380
    password:
    timeout: 60000
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms

# Application specific configuration
app:
  version: 1.0.0
  server:
    url: http://localhost:8090
    
  audit:
    retention-days: 90
    cleanup-schedule: "0 0 1 * * ?" # Run at 1 AM every day
    enabled: true
    
  jwt:
    secret: ${JWT_SECRET:LifeTechSecretKeyForJWTTokenGenerationMustBe256BitsLongForSecurity}
    expiration: 86400000 # 24 hours
    refresh-expiration: 604800000 # 7 days
    
  security:
    max-failed-attempts: 5
    lockout-duration: 1800 # 30 minutes in seconds
    password-history-count: 5
    password-expiry-days: 90
    password-pattern: "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=])(?=\\S+$).{8,}$"
    password-pattern-message: "Password must be at least 8 characters long and contain at least one digit, one lowercase letter, one uppercase letter, and one special character"
    
  encryption:
    key: LifeTechEncryptionKeyForAESGCMMustBe256BitsLongForDataSecurity
    
  blockchain:
    enabled: true
    network: ethereum-testnet
    contract-address: 0x742d35Cc6634C0532925a3b8D4Ad8d0000000000
    gas-limit: 300000
    gas-price: 20000000000  # 20 gwei
    
  file:
    upload:
      max-file-size: 10MB
      max-request-size: 50MB
      allowed-types: jpg,jpeg,png,pdf,doc,docx
      
  email:
    enabled: false
    smtp:
      host: smtp.gmail.com
      port: 587
      username: ${EMAIL_USERNAME:}
      password: ${EMAIL_PASSWORD:}
      auth: true
      starttls: true

# Logging configuration
logging:
  level:
    com.finance.admin: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/lifetech-backend.log

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      show-components: always
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

# Swagger/OpenAPI configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    displayRequestDuration: true
  show-actuator: true

# Database migration
flyway:
  enabled: false  # Disabled for H2 in-memory database
  locations: classpath:db/migration
  baseline-on-migrate: true

---
# Production profile
spring:
  config:
    activate:
      on-profile: production
      
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/lifetech}
    username: ${DATABASE_USERNAME:lifetech}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
      
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
    
  h2:
    console:
      enabled: false

app:
  server:
    url: ${SERVER_URL:https://api.lifetech.com}
    
  jwt:
    secret: ${JWT_SECRET:LifeTechSecretKeyForJWTTokenGenerationMustBe256BitsLongForSecurity}
    
  encryption:
    key: ${ENCRYPTION_KEY:LifeTechEncryptionKeyForAESGCMMustBe256BitsLongForDataSecurity}
    
  blockchain:
    network: ${BLOCKCHAIN_NETWORK:ethereum-mainnet}
    contract-address: ${BLOCKCHAIN_CONTRACT_ADDRESS:}
    private-key: ${BLOCKCHAIN_PRIVATE_KEY:}
    
  email:
    enabled: true
    smtp:
      username: ${EMAIL_USERNAME:}
      password: ${EMAIL_PASSWORD:}

logging:
  level:
    com.finance.admin: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
  file:
    name: /var/log/lifetech/backend.log

flyway:
  enabled: true

---
# Test profile
spring:
  config:
    activate:
      on-profile: test
      
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false

app:
  blockchain:
    enabled: false
    
  email:
    enabled: false

logging:
  level:
    com.finance.admin: WARN
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
