spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/tycoon_admin
    username: admin
    password: password
  
  data:
    mongodb:
      uri: mongodb://mongodb:27017/tycoon_admin_docs
  
  redis:
    host: redis
    port: 6379
    timeout: 2000
    lettuce:
      shutdown-timeout: 200ms
      client:
        type: simple
  
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
