# Removed 'spring.profiles.active' as it should not be set in a profile-specific configuration file.

# Test Configuration
spring:
  # Test Database Configuration
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    
  # JPA Configuration for Tests
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        
  # SQL Initialization
  sql:
    init:
      mode: always
      schema-locations: classpath:test-schema.sql
      data-locations: classpath:test-data.sql
      platform: h2
      continue-on-error: false
      
  # H2 Console for debugging
  h2:
    console:
      enabled: true
      
  # Exclude external services for testing
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
      - org.springframework.boot.autoconfigure.mail.MailSenderAutoConfiguration
      - org.springframework.boot.autoconfigure.security.oauth2.client.servlet.OAuth2ClientAutoConfiguration
      - org.springframework.boot.autoconfigure.batch.BatchAutoConfiguration
    
  # Main configuration
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
    lazy-initialization: true

  # Disable email for tests
  mail:
    enabled: false
    host: localhost
    port: 3025
    username: test
    password: test
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

  # Test-specific Jackson configuration
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

  # Disable Flyway for tests
  flyway:
    enabled: false

  # AWS Configuration for Tests
  aws:
    s3:
      endpoint: http://localhost:4566
      region: us-east-1
      bucket: test-bucket
      
  # Security Configuration for Tests
  security:
    jwt:
      secret: test-secret-key-for-jwt-token-generation-in-tests
      expiration: 3600000

  # RabbitMQ Configuration for Tests
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  # MongoDB Configuration for Tests
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test
      
  # Redis Configuration for Tests
  redis:
    host: localhost
    port: 6379

# Test-specific Application Configuration
app:
  jwt:
    secret: test-secret-key-for-jwt-token-generation-in-tests
    expiration: 3600000
  
  security:
    allowed-ips: 127.0.0.1,::1,192.168.1.0/24
    max-failed-attempts: 3
    lockout-duration: 60000 # 1 minute for tests
    session-timeout: 300000 # 5 minutes for tests
    
  audit:
    retention-days: 7 # Shorter retention for tests
    cleanup-schedule: "0 0 1 * * ?" # Daily at 1 AM
    
  encryption:
    key: testEncryptionKeyForAESGCMMustBe256BitsLongForDataSecurityTesting123456789012345

  # Disable email features for tests
  email:
    enabled: false
    smtp:
      enabled: false
      host: localhost
      port: 3025
      username: test
      password: test
      auth: false
      starttls: false
  
  certificate:
    email:
      enabled: false
      from: test@example.com
      admin: test@example.com

# Logging Configuration
logging:
  level:
    root: WARN
    org.springframework: WARN
    org.springframework.security: DEBUG
    org.springframework.security.authentication: DEBUG
    org.springframework.security.authentication.dao: DEBUG
    org.springframework.test: INFO
    org.springframework.boot.test: INFO
    org.springframework.transaction: WARN
    org.springframework.orm.jpa: WARN
    org.springframework.data.jpa: WARN
    org.hibernate: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    com.finance.admin: DEBUG
    com.finance.admin.auth: DEBUG
    com.zaxxer.hikari: WARN
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Disable actuator endpoints in tests
management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: false

# Server configuration for tests
server:
  port: 0 # Random port for tests
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false
