spring:
  application:
    name: tycoon-admin-management-test
  
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    
  redis:
    host: localhost
    port: 6379
    timeout: 2000ms
    
  data:
    mongodb:
      uri: mongodb://localhost:27017/tycoon_admin_test
      
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# Test-specific configuration
app:
  jwt:
    secret: testSecretKeyForTycoonAdminSystemThatIsAtLeast256BitsLongForTestingPurposes
    expiration: 600000 # 10 minutes for tests
    refresh-expiration: 3600000 # 1 hour for tests
  
  security:
    allowed-ips: 127.0.0.1,::1,192.168.1.0/24
    max-failed-attempts: 3
    lockout-duration: 60000 # 1 minute for tests
    session-timeout: 300000 # 5 minutes for tests
    
  audit:
    retention-days: 30 # Shorter retention for tests
    cleanup-schedule: "0 0 1 * * ?" # Daily at 1 AM

# Logging for tests
logging:
  level:
    com.tycoon.admin: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.springframework.web: WARN
    org.testcontainers: WARN
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Disable actuator endpoints in tests
management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true

# Server configuration for tests
server:
  port: 0 # Random port for tests 